version: '3.8'

services:
  designer:
    container_name: nussknacker_designer
    image: touk/nussknacker:latest
    environment:
      CONFIG_FILE: /opt/nussknacker/conf/nussknacker.conf
      JDK_JAVA_OPTIONS: -Xmx1024M
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      INFLUXDB_URL: http://influxdb:8086
      NUSSKNACKER_LOG_LEVEL: INFO
    ports:
      - 5005:5005
    volumes:
      - storage_designer:/opt/nussknacker/storage
      - ./nussknacker.conf:/opt/nussknacker/conf/nussknacker.conf
      - ./components/components.jar:/opt/nussknacker/components/common/components.jar

  influxdb:
    container_name: nussknacker_influxdb
    hostname: influxdb
    image: influxdb:${INFLUXDB_VERSION-1.8.10}
    ports:
      - "3086:8086"
    environment:
      INFLUXDB_DB: esp
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
      INFLUXDB_HTTP_LOG_ENABLED: "false"
    volumes:
      - storage_influxdb:/var/lib/influxdb

  grafana:
    container_name: nussknacker_grafana
    image: grafana/grafana:${GRAFANA_VERSION-8.4.2}
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana
      - GF_SECURITY_ALLOW_EMBEDDING=true
    depends_on:
      - influxdb

  nginx:
    container_name: nussknacker_nginx
    image: nginx:${NGINX_VERSION-1.17.6}
    ports:
      - "${NGINX_PORT-8099}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 6

  simple-api:
    container_name: simple-api
    build: ./simple-api
    ports:
      - "8098:80"
    volumes:
      - ./simple-api/app:/code/app

volumes:
  storage_designer:
    name: nussknacker_storage_designer
  storage_influxdb:
    name: nussknacker_storage_influxdb

networks:
  default:
    name: nussknacker_network
